application: meetupvote
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /cron
  script: cron.py
  login: admin

- url: /mail
  script: vote.py
  login: admin

- url: /reminder
  script: vote.py
  login: admin

- url: /admin
  script: vote.py
  login: admin

- url: /.*
  script: vote.py
  login: required

